### ISSUE TITLE
Close and open ConversationFragment quickly and frequently will cause app crash

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/skygear-SDK-Android#269]
```
2018-10-03 17:26:31.149 16026-16026/com.pkdev.skygeardemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pkdev.skygeardemo, PID: 16026
    java.lang.IllegalStateException: this.activity must not be null
        at io.skygear.plugins.chat.ui.ConversationFragment.updateTitle(ConversationFragment.kt:345)
        at io.skygear.plugins.chat.ui.ConversationFragment.access$updateTitle(ConversationFragment.kt:41)
        at io.skygear.plugins.chat.ui.ConversationFragment$fetchParticipants$$inlined$let$lambda$1.onSuccess(ConversationFragment.kt:335)
        at io.skygear.plugins.chat.ui.ConversationFragment$fetchParticipants$$inlined$let$lambda$1.onSuccess(ConversationFragment.kt:324)
        at io.skygear.plugins.chat.ChatContainer$24.onSuccess(ChatContainer.java:1435)
        at io.skygear.plugins.chat.ChatContainer$24.onSuccess(ChatContainer.java:1426)
        at io.skygear.plugins.chat.QueryResponseAdapter.onQuerySuccess(QueryResponseAdapter.java:39)
        at io.skygear.skygear.RecordQueryResponseHandler.onSuccess(RecordQueryResponseHandler.java:69)
        at io.skygear.skygear.Request.onResponse(Request.java:123)
        at io.skygear.skygear.Request.onResponse(Request.java:32)
        at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
        at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by carmenlau** [comment]
Moved to chat SDK: https://github.com/SkygearIO/chat-SDK-Android/issues/211
