### ISSUE TITLE
Query on publicDB failed due to parsing on null value of _access field failed

### ISSUE THREAD

**Issue by cpryanpang** [SkygearIO/skygear-SDK-Android#44]
After successful log-on, it is unable to retrieve the record owned by currentUser, from `user` table in publicDB.

- Skygear Android SDK: 0.16.0
- Skygear Server: 0.16.0

## Steps to reproduce
After successful log-on, we performed following:
```
		Container.defaultContainer(this);
		Query query = new Query("user");
		query.equalTo("_id", skygear.getCurrentUser().getId());
		skygear.getPublicDatabase().query(query, new RecordQueryResponseHandler() {
			@Override
			public void onQuerySuccess(Record[] records) {
				// Although the record exists on server database,
				// the SDK cannot reach here
			}

			@Override
			public void onQueryError(String reason) {
				Log.d(TAG, "error = " + reason);
			}
		});
```

## Actual Results
The `onQueryError` callback was invoked, the reason is `Malformed server response`. Following the stack trace, this reason string came from `RecordQueryResponseHandler#onSuccess` since its caught an exception from `Record#fromJson` and `RecordSerializer#deserialize`.

### Response
Below is the json response:
```
{
   "result":[
      {
         "display_name":"Coffee Can",
         "_type":"record",
         "username":"ryanpang",
         "_updated_by":"aed464a7-45b8-4fde-b59b-3c131d996b84",
         "_ownerID":"aed464a7-45b8-4fde-b59b-3c131d996b84",
         "_id":"user\/aed464a7-45b8-4fde-b59b-3c131d996b84",
         "is_active":true,
         "_created_at":"2016-06-29T07:28:37.903873Z",
         "_created_by":"aed464a7-45b8-4fde-b59b-3c131d996b84",
         "_access":null,
         "_updated_at":"2016-06-29T07:28:37.903873Z"
      }
   ]
}
```

(My record on server table `user` really has a `null` value at field `_access`.)

### More Error Logs
By adding some Log.e calls into SDK, it reveals that the exception is raised from `RecordSerializer`, line 164 (some line numbers may differ from yours as I added Log.e):

```
09-06 11:51:13.247 3074-3074/io.skygear.skygear_example E/RecordQueryResHdl: Value null at _access of type org.json.JSONObject$1 cannot be converted to JSONArray
org.json.JSONException: Value null at _access of type org.json.JSONObject$1 cannot be converted to JSONArray
    at org.json.JSON.typeMismatch(JSON.java:100)
    at org.json.JSONObject.getJSONArray(JSONObject.java:552)
    at io.skygear.skygear.RecordSerializer$override.deserialize(RecordSerializer.java:164)
    at io.skygear.skygear.RecordSerializer$override.access$dispatch(RecordSerializer.java)
    at io.skygear.skygear.RecordSerializer.deserialize(RecordSerializer.java:0)
    at io.skygear.skygear.Record.fromJson(Record.java:404)
    at io.skygear.skygear.RecordQueryResponseHandler.onSuccess(RecordQueryResponseHandler.java:36)
    at io.skygear.skygear.Request.onResponse(Request.java:101)
    at io.skygear.skygear.Request.onResponse(Request.java:16)
    at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
    at android.os.Handler.handleCallback(Handler.java:730)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:5225)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
    at dalvik.system.NativeStart.main(Native Method)
```

The essential parts:
```
        // RecordSerializer.java:164
        JSONArray accessJsonArray = null;
        if (jsonObject.has("_access")) {
            accessJsonArray = jsonObject.getJSONArray("_access");
        }
```

**Comment by ben181231** [comment]
Fixed on Commit 004d514
